apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: variables.pharos.py
spec:
  group: pharos.py
  names:
    kind: Variable
    plural: variables
    singular: variable
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          json:
            x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: true
